//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDGraph.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PathHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PathHistory"]));
            }
            set {
                this["PathHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal OptionCalculMaxDepth {
            get {
                return ((decimal)(this["OptionCalculMaxDepth"]));
            }
            set {
                this["OptionCalculMaxDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal OptionDrawMaxDepth {
            get {
                return ((decimal)(this["OptionDrawMaxDepth"]));
            }
            set {
                this["OptionDrawMaxDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionPrintSize {
            get {
                return ((bool)(this["OptionPrintSize"]));
            }
            set {
                this["OptionPrintSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionAutoCompleteGraph {
            get {
                return ((bool)(this["OptionAutoCompleteGraph"]));
            }
            set {
                this["OptionAutoCompleteGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionAllowFolderDeletion {
            get {
                return ((bool)(this["OptionAllowFolderDeletion"]));
            }
            set {
                this["OptionAllowFolderDeletion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionDeletionAsk4Confirmation {
            get {
                return ((bool)(this["OptionDeletionAsk4Confirmation"]));
            }
            set {
                this["OptionDeletionAsk4Confirmation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Linear")]
        public string OptionColorStyle {
            get {
                return ((string)(this["OptionColorStyle"]));
            }
            set {
                this["OptionColorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState OptionMainWindowOpenState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["OptionMainWindowOpenState"]));
            }
            set {
                this["OptionMainWindowOpenState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("762, 592")]
        public global::System.Drawing.Size OptionMainWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["OptionMainWindowSize"]));
            }
            set {
                this["OptionMainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("506, 24")]
        public global::System.Drawing.Point OptionToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["OptionToolbarLocation"]));
            }
            set {
                this["OptionToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionShowFreeSpace {
            get {
                return ((bool)(this["OptionShowFreeSpace"]));
            }
            set {
                this["OptionShowFreeSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionShowSizesInHumanForm {
            get {
                return ((bool)(this["OptionShowSizesInHumanForm"]));
            }
            set {
                this["OptionShowSizesInHumanForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionShowTooltips {
            get {
                return ((bool)(this["OptionShowTooltips"]));
            }
            set {
                this["OptionShowTooltips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int OptionTextDensity {
            get {
                return ((int)(this["OptionTextDensity"]));
            }
            set {
                this["OptionTextDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OptionGraphRotation {
            get {
                return ((int)(this["OptionGraphRotation"]));
            }
            set {
                this["OptionGraphRotation"] = value;
            }
        }
    }
}
