//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.42
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDGraph.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDGraph.Resources.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GB.
        /// </summary>
        internal static string abreviationGOctet {
            get {
                return ResourceManager.GetString("abreviationGOctet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KB.
        /// </summary>
        internal static string abreviationKOctet {
            get {
                return ResourceManager.GetString("abreviationKOctet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MB.
        /// </summary>
        internal static string abreviationMOctet {
            get {
                return ResourceManager.GetString("abreviationMOctet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B..
        /// </summary>
        internal static string abreviationOctet {
            get {
                return ResourceManager.GetString("abreviationOctet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TB.
        /// </summary>
        internal static string abreviationTOctet {
            get {
                return ResourceManager.GetString("abreviationTOctet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A critical error occured. Error is logged, and application will stop. Please send the application log to the HDGraph team (contact: http://hdgraph.sourceforge.net). Thank you..
        /// </summary>
        internal static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cursor hover directory {0}.
        /// </summary>
        internal static string CursorHoverDirectory {
            get {
                return ResourceManager.GetString("CursorHoverDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cursor hover no directory..
        /// </summary>
        internal static string CursorHoverNoDirectory {
            get {
                return ResourceManager.GetString("CursorHoverNoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder successfully deleted !.
        /// </summary>
        internal static string DeletionCompleteMsg {
            get {
                return ResourceManager.GetString("DeletionCompleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HDGraph Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured while deleting folder. Some files were not deleted. Error detail : {0}.
        /// </summary>
        internal static string ErrorDeletingFolder {
            get {
                return ResourceManager.GetString("ErrorDeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error in the configuration file prevent the application to load the appropriate language. Please verify that the langage code is correct in your config file !.
        /// </summary>
        internal static string ErrorInConfigLanguage {
            get {
                return ResourceManager.GetString("ErrorInConfigLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language code error in config file.
        /// </summary>
        internal static string ErrorInConfigLanguageTitle {
            get {
                return ResourceManager.GetString("ErrorInConfigLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading {0} : {1}.
        /// </summary>
        internal static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading file {0}. Load action canceled. Error detail : .
        /// </summary>
        internal static string ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Draw space with HDGraph.
        /// </summary>
        internal static string ExplorerContextMenuAction {
            get {
                return ResourceManager.GetString("ExplorerContextMenuAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected folder is empty..
        /// </summary>
        internal static string FolderIsEmpty {
            get {
                return ResourceManager.GetString("FolderIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will permanently delete the folder &quot;{0}&quot; and all its content. Are you sure ?.
        /// </summary>
        internal static string GoingToDeleteFolderMsg {
            get {
                return ResourceManager.GetString("GoingToDeleteFolderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your are about to delete a folder.
        /// </summary>
        internal static string GoingToDeleteFolderTitle {
            get {
                return ResourceManager.GetString("GoingToDeleteFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step by step instructions :
        ///1) Choose a directory to analyse on the top combo box.
        ///2) Press the &quot;Scan / Refresh&quot; button.
        ///3) Wait for the end of the analysis..
        /// </summary>
        internal static string GraphGuideLine {
            get {
                return ResourceManager.GetString("GraphGuideLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyze loaded. Disk snapshot date is {0}..
        /// </summary>
        internal static string GraphLoadedFromDate {
            get {
                return ResourceManager.GetString("GraphLoadedFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graph refresh completed !.
        /// </summary>
        internal static string GraphRefreshed {
            get {
                return ResourceManager.GetString("GraphRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HDG is currently NOT integrated in the explorer context menu. Nothing to do !.
        /// </summary>
        internal static string HdgAlreadyDesIntegratedInExplorer {
            get {
                return ResourceManager.GetString("HdgAlreadyDesIntegratedInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HDG has already been integrated in the explorer. Nothing to do !.
        /// </summary>
        internal static string HdgAlreadyIntegratedInExplorer {
            get {
                return ResourceManager.GetString("HdgAlreadyIntegratedInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HDG has been successfully removed from the explorer context menu..
        /// </summary>
        internal static string HdgCorrectlyDesIntegratedInExplorer {
            get {
                return ResourceManager.GetString("HdgCorrectlyDesIntegratedInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Integration successfull ! Try to right click on a folder....
        /// </summary>
        internal static string HdgCorrectlyIntegratedInExplorer {
            get {
                return ResourceManager.GetString("HdgCorrectlyIntegratedInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HDG is a free tool allowing to graphically display the hard disk space usage. It shows all the directories and subdirectories of the hard drive on a single graph, allowing to see the the largest directories at a glance..
        /// </summary>
        internal static string HdgDescription {
            get {
                return ResourceManager.GetString("HdgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HDG Graphics Files.
        /// </summary>
        internal static string HDGFiles {
            get {
                return ResourceManager.GetString("HDGFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This program is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU Lesser General Public
        ///License as published by the Free Software Foundation; either
        ///version 2.1 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
        ///Lesser General Public License for more details.
        ///
        ///You should [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string HdgLicenceDescription {
            get {
                return ResourceManager.GetString("HdgLicenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence : GNU Lesser General Public License (LGPL).
        /// </summary>
        internal static string HdgLicenceName {
            get {
                return ResourceManager.GetString("HdgLicenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HDGraph-en.chm.
        /// </summary>
        internal static string HelpFilename {
            get {
                return ResourceManager.GetString("HelpFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path history list successfully cleared !.
        /// </summary>
        internal static string HistorySuccessfullyCleared {
            get {
                return ResourceManager.GetString("HistorySuccessfullyCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load file: it has been created with an incompatible version of HDGraph..
        /// </summary>
        internal static string IncompatibleVersionError {
            get {
                return ResourceManager.GetString("IncompatibleVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified path is not valid. Please verify it ! Scan aborted..
        /// </summary>
        internal static string InvalidPathError {
            get {
                return ResourceManager.GetString("InvalidPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language setting has been modified. Until you restart the application, only new windows will use the correct settings..
        /// </summary>
        internal static string languageApplied {
            get {
                return ResourceManager.GetString("languageApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage setting modified !.
        /// </summary>
        internal static string languageAppliedTitle {
            get {
                return ResourceManager.GetString("languageAppliedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à none.
        /// </summary>
        internal static string languageId {
            get {
                return ResourceManager.GetString("languageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading language list....
        /// </summary>
        internal static string loadingLanguageList {
            get {
                return ResourceManager.GetString("loadingLanguageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation failed.
        /// </summary>
        internal static string OperationFailedTitle {
            get {
                return ResourceManager.GetString("OperationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation successfull.
        /// </summary>
        internal static string OperationSuccessfullTitle {
            get {
                return ResourceManager.GetString("OperationSuccessfullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose the directory to analyse :.
        /// </summary>
        internal static string PleaseChooseDirectory {
            get {
                return ResourceManager.GetString("PleaseChooseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scanning .
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready..
        /// </summary>
        internal static string statusReady {
            get {
                return ResourceManager.GetString("statusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error prevent you to do the operation. Perhaps that you don&apos;t have rights to do this (try as administrator if you&apos;re not). Error detail : {0}..
        /// </summary>
        internal static string UnableToDesIntegrateInExplorer {
            get {
                return ResourceManager.GetString("UnableToDesIntegrateInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error prevent you to do the operation. Perhaps that you don&apos;t have rights to do this (try as administrator if you&apos;re not). Error detail : {0}..
        /// </summary>
        internal static string UnableToIntegrateInExplorer {
            get {
                return ResourceManager.GetString("UnableToIntegrateInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occured during scan. It has been logged. Please send the application log to the HDGraph team (contact: http://hdgraph.sourceforge.net). Thank you..
        /// </summary>
        internal static string UnexpectedErrorDuringAnalysis {
            get {
                return ResourceManager.GetString("UnexpectedErrorDuringAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory scan has been aborted by user. Please launch a new scan..
        /// </summary>
        internal static string UserCanceledAnalysis {
            get {
                return ResourceManager.GetString("UserCanceledAnalysis", resourceCulture);
            }
        }
    }
}
