#define IDH_hdgraph__introduction 2
#define IDH_qu_est_ce_que_hdgraph__ 6
#define IDH_page_un_1 0
#define IDH_utiliser_hdgraph 11
#define IDH_pour_commencer___ 10
#define IDH_fonctions_de_base 14
#define IDH_utilisation_avancee 57
#define IDH_niveaux_de_repertoires_memorises 50
#define IDH_niveaux_de_repertoires_a_dessiner__zoom_ 51
#define IDH_menus 29
#define IDH_menu_fichier 32
#define IDH_menu_affichage 33
#define IDH_menu_outils 54
#define IDH_options 30
#define IDH_afficher_les_tailles_des_repertoires 52
#define IDH_completer_automatiquement_le_graphe_pend 53
#define IDH_index_des_mots_clefs 26
#define IDH_glossaire 4
#define IDH_resultat 23
#define IDH_table_des_matieres 42
#define IDH_table_des_illustrations 3
