//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDGraph.WpfDrawEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDGraph.WpfDrawEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string AccelerationTypeFull {
            get {
                return ResourceManager.GetString("AccelerationTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The higher level of acceleration is used, thanks to your graphic card..
        /// </summary>
        public static string AccelerationTypeFullDesc {
            get {
                return ResourceManager.GetString("AccelerationTypeFullDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None !.
        /// </summary>
        public static string AccelerationTypeNone {
            get {
                return ResourceManager.GetString("AccelerationTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your graphic card isn&apos;t powerfull enough to help drawing the graph. Performances should be very bad. You are advised to set the &quot;Basic&quot; draw engine in the avanced options..
        /// </summary>
        public static string AccelerationTypeNoneDesc {
            get {
                return ResourceManager.GetString("AccelerationTypeNoneDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        public static string AccelerationTypePartial {
            get {
                return ResourceManager.GetString("AccelerationTypePartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your graphic card partially helps to draw the graph, but is not very powerfull. Performances can be poor. You should set the &quot;Basic&quot; draw engine in the avanced options..
        /// </summary>
        public static string AccelerationTypePartialDesc {
            get {
                return ResourceManager.GetString("AccelerationTypePartialDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string AccelerationTypeUnknown {
            get {
                return ResourceManager.GetString("AccelerationTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has prevented determining the acceleration level available for your graphic card..
        /// </summary>
        public static string AccelerationTypeUnknownDesc {
            get {
                return ResourceManager.GetString("AccelerationTypeUnknownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center graph on this directory.
        /// </summary>
        public static string ContextMenuCenterOnThis {
            get {
                return ResourceManager.GetString("ContextMenuCenterOnThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete permanently.
        /// </summary>
        public static string ContextMenuDeletePermanently {
            get {
                return ResourceManager.GetString("ContextMenuDeletePermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this directory and all subdirectories.
        /// </summary>
        public static string ContextMenuDeleteThis {
            get {
                return ResourceManager.GetString("ContextMenuDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in external window.
        /// </summary>
        public static string ContextMenuOpenExternal {
            get {
                return ResourceManager.GetString("ContextMenuOpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh this directory.
        /// </summary>
        public static string ContextMenuRefreshThis {
            get {
                return ResourceManager.GetString("ContextMenuRefreshThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ContextMenuShowDetails {
            get {
                return ResourceManager.GetString("ContextMenuShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware acceleration: .
        /// </summary>
        public static string HardwareAcceleration {
            get {
                return ResourceManager.GetString("HardwareAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are hidden folders here. {0}To show them, center the graph on their parent (&quot;{1}&quot;) with a double click..
        /// </summary>
        public static string HiddenFolders {
            get {
                return ResourceManager.GetString("HiddenFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation:.
        /// </summary>
        public static string LabelRotation {
            get {
                return ResourceManager.GetString("LabelRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text size:.
        /// </summary>
        public static string LabelTextSize {
            get {
                return ResourceManager.GetString("LabelTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size:.
        /// </summary>
        public static string LabelTotalSize {
            get {
                return ResourceManager.GetString("LabelTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View options.
        /// </summary>
        public static string LabelViewOptions {
            get {
                return ResourceManager.GetString("LabelViewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string LabelZoom {
            get {
                return ResourceManager.GetString("LabelZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many small folders to show them individually. {0}To show them, center the graph on their parent (&quot;{1}&quot;) with a double click, or open the &quot;Details&quot; window of this parent..
        /// </summary>
        public static string MultipleSmallFolders {
            get {
                return ResourceManager.GetString("MultipleSmallFolders", resourceCulture);
            }
        }
    }
}
